export const PAGE_TITLES = {
	landing: "Welcome",
	dashboard: "Dashboard",
	batch: "Batch Details",
	batchRecords: "Batch Records",
	deliveryOrder: "Delivery Order Details",
	deliveryOrders: "Delivery Orders",
	deliveryReceipt: "Delivery Receipt Details",
	deliveryReceipts: "Delivery Receipts",
	deliveryRequest: "Delivery Request Details",
	deliveryRequests: "Delivery Requests",
	department: "Department Details",
	departments: "Departments",
	newDeliveryOrder: "New Delivery Order",
	newDeliveryReceipt: "New Delivery Receipt",
	patient: "Patient Details",
	patients: "Patients",
	product: "Product Details",
	products: "Products",
	reports: "Reports",
	stockMovement: "Stock Movement",
	stockRecords: "Stock Records",
	supplier: "Supplier Details",
	suppliers: "Suppliers",
	userManagement: "User Management",
	userProfile: "User Profile",
	approverDashboard: "Approver Dashboard",
	approverLayout: "Approver",
	requestDetail: "Request Details",
	requestList: "Request List",
	login: "Login",
};
