// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/facility": {
    params: {};
  };
  "/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/reservation/confirmation": {
    params: {};
  };
  "/reservation/complete": {
    params: {};
  };
  "/location-test": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/sports": {
    params: {};
  };
  "/lifestyle": {
    params: {};
  };
  "/facility/:id/photos": {
    params: {
      "id": string;
    };
  };
  "/event/:id": {
    params: {
      "id": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/reservation": {
    params: {};
  };
  "/admin/reservation/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/facility": {
    params: {};
  };
  "/admin/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/facility/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/user": {
    params: {};
  };
  "/admin/deal": {
    params: {};
  };
  "/admin/profile": {
    params: {};
  };
  "/admin/facility/:id/photos": {
    params: {
      "id": string;
    };
  };
  "/scheduling/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/scheduling/reservation/confirmation": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin/login" | "/facility" | "/facility/:id" | "/reservation/confirmation" | "/reservation/complete" | "/location-test" | "/profile" | "/profile/edit" | "/sports" | "/lifestyle" | "/facility/:id/photos" | "/event/:id" | "/admin" | "/admin/dashboard" | "/admin/reservation" | "/admin/reservation/:id" | "/admin/facility" | "/admin/facility/:id" | "/admin/facility/:id/edit" | "/admin/user" | "/admin/deal" | "/admin/profile" | "/admin/facility/:id/photos" | "/scheduling/facility/:id" | "/scheduling/reservation/confirmation" | "/*";
  };
  "layouts/auth-layout.tsx": {
    id: "layouts/auth-layout";
    page: "/admin/login";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/admin/login";
  };
  "layouts/user-layout.tsx": {
    id: "layouts/user-layout";
    page: "/" | "/facility" | "/facility/:id" | "/reservation/confirmation" | "/reservation/complete" | "/location-test" | "/profile" | "/profile/edit" | "/sports" | "/lifestyle" | "/facility/:id/photos" | "/event/:id";
  };
  "routes/user/landing.tsx": {
    id: "routes/user/landing";
    page: "/";
  };
  "routes/user/filtered-facilities.tsx": {
    id: "routes/user/filtered-facilities";
    page: "/facility";
  };
  "routes/user/facility.tsx": {
    id: "routes/user/facility";
    page: "/facility/:id";
  };
  "routes/user/booking-confirmation.tsx": {
    id: "routes/user/booking-confirmation";
    page: "/reservation/confirmation";
  };
  "routes/user/booking-complete.tsx": {
    id: "routes/user/booking-complete";
    page: "/reservation/complete";
  };
  "routes/user/location-test.tsx": {
    id: "routes/user/location-test";
    page: "/location-test";
  };
  "routes/user/profile.tsx": {
    id: "routes/user/profile";
    page: "/profile";
  };
  "routes/user/edit-profile.tsx": {
    id: "routes/user/edit-profile";
    page: "/profile/edit";
  };
  "routes/user/sports.tsx": {
    id: "routes/user/sports";
    page: "/sports";
  };
  "routes/user/lifestyle.tsx": {
    id: "routes/user/lifestyle";
    page: "/lifestyle";
  };
  "routes/user/facility-photos.tsx": {
    id: "routes/user/facility-photos";
    page: "/facility/:id/photos";
  };
  "routes/user/event.tsx": {
    id: "routes/user/event";
    page: "/event/:id";
  };
  "layouts/admin-layout.tsx": {
    id: "layouts/admin-layout";
    page: "/admin" | "/admin/dashboard" | "/admin/reservation" | "/admin/reservation/:id" | "/admin/facility" | "/admin/facility/:id" | "/admin/facility/:id/edit" | "/admin/user" | "/admin/deal" | "/admin/profile" | "/admin/facility/:id/photos";
  };
  "routes/admin/admin.tsx": {
    id: "routes/admin/admin";
    page: "/admin";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/reservations.tsx": {
    id: "routes/admin/reservations";
    page: "/admin/reservation";
  };
  "routes/admin/reservation.tsx": {
    id: "routes/admin/reservation";
    page: "/admin/reservation/:id";
  };
  "routes/admin/facilities.tsx": {
    id: "routes/admin/facilities";
    page: "/admin/facility";
  };
  "routes/admin/facility.tsx": {
    id: "routes/admin/facility";
    page: "/admin/facility/:id";
  };
  "routes/admin/edit-facility.tsx": {
    id: "routes/admin/edit-facility";
    page: "/admin/facility/:id/edit";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/user";
  };
  "routes/admin/deals.tsx": {
    id: "routes/admin/deals";
    page: "/admin/deal";
  };
  "routes/admin/profile.tsx": {
    id: "routes/admin/profile";
    page: "/admin/profile";
  };
  "routes/admin/facility-photos.tsx": {
    id: "routes/admin/facility-photos";
    page: "/admin/facility/:id/photos";
  };
  "layouts/scheduling-layout.tsx": {
    id: "layouts/scheduling-layout";
    page: "/scheduling/facility/:id" | "/scheduling/reservation/confirmation";
  };
  "routes/scheduling/facility.tsx": {
    id: "routes/scheduling/facility";
    page: "/scheduling/facility/:id";
  };
  "routes/scheduling/reservation-confirmation.tsx": {
    id: "routes/scheduling/reservation-confirmation";
    page: "/scheduling/reservation/confirmation";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/auth-layout": typeof import("./app/layouts/auth-layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "layouts/user-layout": typeof import("./app/layouts/user-layout.tsx");
  "routes/user/landing": typeof import("./app/routes/user/landing.tsx");
  "routes/user/filtered-facilities": typeof import("./app/routes/user/filtered-facilities.tsx");
  "routes/user/facility": typeof import("./app/routes/user/facility.tsx");
  "routes/user/booking-confirmation": typeof import("./app/routes/user/booking-confirmation.tsx");
  "routes/user/booking-complete": typeof import("./app/routes/user/booking-complete.tsx");
  "routes/user/location-test": typeof import("./app/routes/user/location-test.tsx");
  "routes/user/profile": typeof import("./app/routes/user/profile.tsx");
  "routes/user/edit-profile": typeof import("./app/routes/user/edit-profile.tsx");
  "routes/user/sports": typeof import("./app/routes/user/sports.tsx");
  "routes/user/lifestyle": typeof import("./app/routes/user/lifestyle.tsx");
  "routes/user/facility-photos": typeof import("./app/routes/user/facility-photos.tsx");
  "routes/user/event": typeof import("./app/routes/user/event.tsx");
  "layouts/admin-layout": typeof import("./app/layouts/admin-layout.tsx");
  "routes/admin/admin": typeof import("./app/routes/admin/admin.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/reservations": typeof import("./app/routes/admin/reservations.tsx");
  "routes/admin/reservation": typeof import("./app/routes/admin/reservation.tsx");
  "routes/admin/facilities": typeof import("./app/routes/admin/facilities.tsx");
  "routes/admin/facility": typeof import("./app/routes/admin/facility.tsx");
  "routes/admin/edit-facility": typeof import("./app/routes/admin/edit-facility.tsx");
  "routes/admin/users": typeof import("./app/routes/admin/users.tsx");
  "routes/admin/deals": typeof import("./app/routes/admin/deals.tsx");
  "routes/admin/profile": typeof import("./app/routes/admin/profile.tsx");
  "routes/admin/facility-photos": typeof import("./app/routes/admin/facility-photos.tsx");
  "layouts/scheduling-layout": typeof import("./app/layouts/scheduling-layout.tsx");
  "routes/scheduling/facility": typeof import("./app/routes/scheduling/facility.tsx");
  "routes/scheduling/reservation-confirmation": typeof import("./app/routes/scheduling/reservation-confirmation.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};