// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/booking/confirmation": {
    params: {};
  };
  "/booking/complete": {
    params: {};
  };
  "/location-test": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/sports": {
    params: {};
  };
  "/lifestyle": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/booking": {
    params: {};
  };
  "/admin/booking/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/facility": {
    params: {};
  };
  "/admin/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/user": {
    params: {};
  };
  "/admin/deal": {
    params: {};
  };
  "/scheduling/facility/:id": {
    params: {
      "id": string;
    };
  };
  "/scheduling/reservation/confirmation": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/facility/:id" | "/booking/confirmation" | "/booking/complete" | "/location-test" | "/profile" | "/sports" | "/lifestyle" | "/admin" | "/admin/dashboard" | "/admin/booking" | "/admin/booking/:id" | "/admin/facility" | "/admin/facility/:id" | "/admin/user" | "/admin/deal" | "/scheduling/facility/:id" | "/scheduling/reservation/confirmation" | "/*";
  };
  "layouts/auth-layout.tsx": {
    id: "layouts/auth-layout";
    page: "/login";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "layouts/user-layout.tsx": {
    id: "layouts/user-layout";
    page: "/" | "/facility/:id" | "/booking/confirmation" | "/booking/complete" | "/location-test" | "/profile" | "/sports" | "/lifestyle";
  };
  "routes/user/landing.tsx": {
    id: "routes/user/landing";
    page: "/";
  };
  "routes/user/facility.tsx": {
    id: "routes/user/facility";
    page: "/facility/:id";
  };
  "routes/user/booking-confirmation.tsx": {
    id: "routes/user/booking-confirmation";
    page: "/booking/confirmation";
  };
  "routes/user/booking-complete.tsx": {
    id: "routes/user/booking-complete";
    page: "/booking/complete";
  };
  "routes/user/location-test.tsx": {
    id: "routes/user/location-test";
    page: "/location-test";
  };
  "routes/user/profile.tsx": {
    id: "routes/user/profile";
    page: "/profile";
  };
  "routes/user/sports.tsx": {
    id: "routes/user/sports";
    page: "/sports";
  };
  "routes/user/lifestyle.tsx": {
    id: "routes/user/lifestyle";
    page: "/lifestyle";
  };
  "layouts/admin-layout.tsx": {
    id: "layouts/admin-layout";
    page: "/admin" | "/admin/dashboard" | "/admin/booking" | "/admin/booking/:id" | "/admin/facility" | "/admin/facility/:id" | "/admin/user" | "/admin/deal";
  };
  "routes/admin/admin.tsx": {
    id: "routes/admin/admin";
    page: "/admin";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/bookings.tsx": {
    id: "routes/admin/bookings";
    page: "/admin/booking";
  };
  "routes/admin/booking.tsx": {
    id: "routes/admin/booking";
    page: "/admin/booking/:id";
  };
  "routes/admin/facilities.tsx": {
    id: "routes/admin/facilities";
    page: "/admin/facility";
  };
  "routes/admin/facility.tsx": {
    id: "routes/admin/facility";
    page: "/admin/facility/:id";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/user";
  };
  "routes/admin/deals.tsx": {
    id: "routes/admin/deals";
    page: "/admin/deal";
  };
  "layouts/scheduling-layout.tsx": {
    id: "layouts/scheduling-layout";
    page: "/scheduling/facility/:id" | "/scheduling/reservation/confirmation";
  };
  "routes/scheduling/facility.tsx": {
    id: "routes/scheduling/facility";
    page: "/scheduling/facility/:id";
  };
  "routes/scheduling/reservation-confirmation.tsx": {
    id: "routes/scheduling/reservation-confirmation";
    page: "/scheduling/reservation/confirmation";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/auth-layout": typeof import("./app/layouts/auth-layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "layouts/user-layout": typeof import("./app/layouts/user-layout.tsx");
  "routes/user/landing": typeof import("./app/routes/user/landing.tsx");
  "routes/user/facility": typeof import("./app/routes/user/facility.tsx");
  "routes/user/booking-confirmation": typeof import("./app/routes/user/booking-confirmation.tsx");
  "routes/user/booking-complete": typeof import("./app/routes/user/booking-complete.tsx");
  "routes/user/location-test": typeof import("./app/routes/user/location-test.tsx");
  "routes/user/profile": typeof import("./app/routes/user/profile.tsx");
  "routes/user/sports": typeof import("./app/routes/user/sports.tsx");
  "routes/user/lifestyle": typeof import("./app/routes/user/lifestyle.tsx");
  "layouts/admin-layout": typeof import("./app/layouts/admin-layout.tsx");
  "routes/admin/admin": typeof import("./app/routes/admin/admin.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/bookings": typeof import("./app/routes/admin/bookings.tsx");
  "routes/admin/booking": typeof import("./app/routes/admin/booking.tsx");
  "routes/admin/facilities": typeof import("./app/routes/admin/facilities.tsx");
  "routes/admin/facility": typeof import("./app/routes/admin/facility.tsx");
  "routes/admin/users": typeof import("./app/routes/admin/users.tsx");
  "routes/admin/deals": typeof import("./app/routes/admin/deals.tsx");
  "layouts/scheduling-layout": typeof import("./app/layouts/scheduling-layout.tsx");
  "routes/scheduling/facility": typeof import("./app/routes/scheduling/facility.tsx");
  "routes/scheduling/reservation-confirmation": typeof import("./app/routes/scheduling/reservation-confirmation.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};